tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "mas"
brew "nkf"
brew "node"
cask "caffeine"
cask "clipy"
cask "google-chrome"
cask "iterm2"
cask "krisp"
cask "visual-studio-code"
cask "zoom"
mas "1Password 7", id: 1333542190
mas "AdGuard for Safari", id: 1440147259
mas "Adobe Lightroom", id: 1451544217
mas "BetterSnapTool", id: 417375580
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
